### PR TITLE
Switch to system libjq

### PR DESCRIPTION
**Pull request by jeroen**
Removes the bundled `jq` and links to system `libjq` instead. Currently this works on Windows, OSX and Fedora, but not Debian/Ubuntu because `libjq-dev` is not yet available there. Hopefully it will become available soon. You can leave this PR open until then...

### CODE REVIEW

**Comment by sckott** [comment]
@jeroenooms where can I look to see if `libjq-dev` is on Debian yet?

**Comment by jeroenooms** [comment]
I don't think so yet: https://packages.debian.org/sid/jq. @else ?

**Comment by else** [comment]
Sorry for the late reply guys, I'll try to work on getting libjq into Debian on the weekend.

**Comment by sckott** [comment]
no worries, & thanks for the help

**Comment by sckott** [comment]
i think this https://packages.debian.org/search?keywords=jq suggests we are ready to go?

**Comment by else** [comment]
Nope, that package is still missing libjq, which is what I'm working on getting into Debian.

**Comment by sckott** [comment]
woops, thanks for clarifying! (i'm not familiar with debian pkgs)

**Comment by jeroenooms** [comment]
@else would it help if I have a first pass at this, and give you a working `debian` for you to review/tweak before submitting?

**Comment by jeroen** [comment]
Closing in favor of https://github.com/ropensci/jqr/pull/59

**Pull request closed without merging**
